### ISSUE TITLE
Update to 0.6.1 Snapshot?

### ISSUE THREAD

**Issue by gowthamnatarajan** [rubenfiszel/rl4j-examples#1]
Can this be updated to 0.6.1 Snapshot of rl4j? I think the package structure has changed.

**Comment by rubenfiszel** [comment]
Hello,

I accept pull request but I don't have time to handle it myself.

**Comment by gowthamnatarajan** [comment]
Ok, will send a request. But there are other errors in related packages. Have created another issue here.
