### ISSUE TITLE
save and load function

### ISSUE THREAD

**Issue by Ceubex** [rubenfiszel/rl4j-examples#3]
I have see the play function of a DQNPolicy do not work with a MDP<MyState, Integer, DiscreteSpace> argument
I do not know why, because it is that is shown in the hardtoy

Another problem is when I load a policy, it is impossible to continue to learn. Why we can just serialize the policy ? It will be simpler if we can serialize DataManager, QLearningDiscreteDense and MDP to continue to learn when we have new data.

It can be a big serialization but it is very useful I think

**Comment by rubenfiszel** [comment]
Please ask for support on https://github.com/deeplearning4j/dl4j-examples. They cover rl4j-examples too.
